import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav  style={{width:"100%",backgroundColor:"red" ,fontSize:"33px",padding:"22px"}}>
          <Link href="/articles">
          articles 
          </Link>
          <Link href="/posts" style={{marginLeft:"20px"}}>
          posts 
          </Link>
          <Link href="/" style={{marginLeft:"20px"}}>
         Home
          </Link>
        </nav>
        {children}</body>
    </html>
  );
}
